### PR TITLE
Use Data.Sequence instead of List

### PR DESCRIPTION
**Pull request by qnikst**
Data List append (++) has O(N^2) complexity, and
we havily use it to create instruction list.

### CODE REVIEW

**Comment by dmatveev** [comment]
Thanks! It is really useful.

**Comment by dmatveev** [comment]
BTW, how had you managed to get that 4x speed-up? On my side, the master became just slower (0.37 -> 0.51s)

**Comment by qnikst** [comment]
iteresting, can't reproduce my previous results, ok. Will fix :)

**Comment by dmatveev** [comment]
Switching from `(Seq Instruction)` to `[Instruction]` for execute's main loop returned the result back to 0.38s in my case.

```
diff --git a/Asm.hs b/Asm.hs
index bf44da4..ea42f9f 100644
--- a/Asm.hs
+++ b/Asm.hs
@@ -8,6 +8,7 @@ import Control.Monad.Trans (liftIO)
 import Control.Monad.Trans.State.Strict
 import           Data.Sequence (Seq, ViewL(..), (<|), (|>), (><))
 import qualified Data.Sequence as Seq
+import Data.Foldable (toList)

 import System.IO

@@ -44,8 +45,8 @@ type Instruction = (Operator, Operand, Operand)

 type ASM a = State (Seq Instruction) a

-compile :: ASM a -> (Seq Instruction)
-compile c = execState c Seq.empty
+compile :: ASM a -> [Instruction]
+compile c = toList $ execState c Seq.empty

 op :: (OperandClass s, OperandClass d) => Operator -> s -> d -> ASM ()
 op cmd src dst = modify $ \s -> s |> (cmd, toOperand src, toOperand dst)
@@ -86,22 +87,21 @@ initialRs = Registers

 type CPU a = StateT Registers IO a

-execute ::Registers -> Seq Instruction -> IO Registers
+execute ::Registers -> [Instruction] -> IO Registers
 execute rs code = execStateT (exec code) rs
   where
    {-# INLINE exec #-}
-   exec s = case Seq.viewl s of
-     EmptyL  -> return ()
-     i :< is -> run i >>= exec
+   exec []     = return ()
+   exec (i:is) = run i >>= exec
        where
-         run (JMP, I pos, _    ) = {-# SCC "JMP" #-} return $! Seq.drop pos code
+         run (JMP, I pos, _    ) = {-# SCC "JMP" #-} return $! drop pos code
          run (JMF,   reg, I pos) = {-# SCC "JMF" #-} readVal reg >>= \v ->
                                                        return $! if toBool v
                                                                  then is
-                                                                 else Seq.drop pos code
+                                                                 else drop pos code
          run (JMT,   reg, I pos) = {-# SCC "JMT" #-} readVal reg >>= \v ->
                                                            return $! if toBool v
-                                                                     then Seq.drop pos code
+                                                                     then drop pos code
                                                                      else is
          run ((ins,   src,   dst)) = {-# SCC "OP"  #-} execOP ins src dst >> return is
```

**Pull request merged**
