### PR TITLE
:)

### PR DESCRIPTION
**Pull request by qnikst**

### CODE REVIEW

**Comment by dmatveev** [comment]
Can you pls rebase these changes on the latest `master`?

**Comment by qnikst** [comment]
Yep, done.

**Comment by dmatveev** [comment]
Thanks!

**Comment by qnikst** [comment]
```
                                                                                             individual     inherited
COST CENTRE                             MODULE                             no.     entries  %time %alloc   %time %alloc

MAIN                                    MAIN                               187           0    0.0    0.9     0.0  100.0
 main                                   Main                               375           0    0.0    0.0     0.0   20.1
  main.\                                Main                               377           2    0.0    0.0     0.0    2.7
   ITER                                 Main                               378           2    0.0    0.3     0.0    2.7
    execute                             Main                               379           2    0.0    1.6     0.0    2.4
     OP                                 Main                               410           2    0.0    0.5     0.0    0.8
      MOV                               Main                               411           2    0.0    0.4     0.0    0.4
  READ                                  Main                               376           1    0.0   17.5     0.0   17.5
 CAF:main1                              Main                               372           0    0.0    0.0     0.0    0.0
  main                                  Main                               374           1    0.0    0.0     0.0    0.0
 CAF:main11                             Main                               370           0    0.0    2.7     0.0    2.7
 CAF:h_rf7V                             Main                               367           0    0.0    0.0     0.0    5.5
  main                                  Main                               382           0    0.0    0.0     0.0    5.5
   main.h                               Main                               383           1    0.0    0.0     0.0    5.5
    compile                             Main                               384           1    0.0    2.4     0.0    5.5
     heron                              Main                               386           0    0.0    1.5     0.0    3.0
      op                                Main                               396           2    0.0    0.0     0.0    1.5
       op.\                             Main                               409          12    0.0    1.5     0.0    1.5
```

not sure if we can do much improvements without losing expressiveness. 
Other possible options are:
- Manual state monad unrolling, i.e.
  
  ``` haskell
  exec = StateT $ \(CpuState s r) -> ...
  ```
  - Using `ST` instead of `State` then registers /memory and other things can be expressed like `STRef`
  - It's possible that making execOP pure can lead to a benefit.

But all those options comes with cost, 1. - is harder to read, 2. - we are losing persistence property, 3 - require a bit of refactoring to make it sane.

So ideally this code should be written in more expressive way without loosing it's speed, and then there can be one more attempt to speedup. But I'm not sure if you are interested in :)

**Comment by dmatveev** [comment]
I am not sure but looks like it does not work.

```
*Main> let h = compile heron
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package containers-0.5.0.0 ... linking ... done.
Loading package bytestring-0.10.0.2 ... linking ... done.
Loading package primitive-0.5.4.0 ... linking ... done.
Loading package vector-0.10.12.2 ... linking ... done.
Loading package transformers-0.4.2.0 ... linking ... done.
Loading package mtl-2.2.1 ... linking ... done.
*Main> h
fromList [(MOV,V 1.0,R R5),(MOV,V 0.0,R R3),(MOV,R R3,R R4),(EQUAL,R R2,R R4),(JMT,R R4,I 12),(MOV,R R1,R R6),(DIV,R R5,R R6),(ADD,R R5,R R6),(MUL,V 0.5,R R6),(MOV,R R6,R R5),(ADD,V 1.0,R R3),(JMP,I 2,N),(PRN,R R6,N)]
*Main> execute (initialRs {r1 = 25, r2 = 4}) h
*Main> 
```

Does `master` work fine for you?

BTW, I  also noticed that the `PRN` is commented out in the "assembly" code, it is not fair :)

**Comment by qnikst** [comment]
My bad :/ and it's even works slowly when fixed, will push in few mins

**Comment by qnikst** [comment]
Seems I've failed to improve this much, but as you can check using -DCRI, execution takes not that much time :)

**Pull request merged**
